### ISSUE TITLE
Error: Cannot find module 'gulp-util'

### ISSUE THREAD

**Issue by cdll** [openks/gulp-pre-link#1]
here s my task below:

```
let prelink= require('gulp-pre-link')
gulp.task('prelink', ()=>{
  return gulp.src('src/*.html)
  .pipe(prelink({}))
  .pipe(gulp.dest('build/'))
})
```

but is there any dependences that was dismissed caused i got an error msg like:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

could u help with it~

**Comment by openks** [comment]
from the msg 'gulp-util' is depended ,i will check other dependences on monday，sorry about that!

**Comment by cdll** [comment]
that will be nice and thanks for the reply~now i manualy had 'gulp-util' package installed and the task run into work but i had another problem [here](https://github.com/openks/gulp-pre-link/issues/2).
